### ISSUE TITLE
Trusted Users can be a group of which you are part

### ISSUE THREAD

**Issue by dysinger** [juspay/nix-browser#104]
Putting yourself into a group of trusted users is also valid.
```
❌ Trusted Users
   trusted-users = @wheel
   User 'xyz' not present in trusted_users
   Add `nix.trustedUsers = [ "root" "xyz" ];` to your nixos configuration
```

This is in the nix manual:
![image](https://github.com/juspay/nix-browser/assets/447/ab1231ef-5866-4e6d-9f26-48426ea25f81)

**Comment by aravindgopall** [comment]
#110
