### ISSUE TITLE
Add end to end testing

### ISSUE THREAD

**Issue by srid** [juspay/nix-browser#11]
We want to test the final `nix build` web app. 

The official leptos templates use [playwright](https://playwright.dev/) to do this:

https://github.com/leptos-rs/start-axum/tree/main/end2end

While we may do the same, I'd like to first explore (briefly) the option of being able to write tests in pure Rust.  For eg., there is playwright-rust, but it seems [unmaintained](https://github.com/octaltree/playwright-rust/pull/49#issuecomment-1564119957). Are there other options? 

Exhausting all that, we may just use something like playwright.

**Comment by srid** [comment]
There is also: https://github.com/stevepryde/thirtyfour

**Comment by srid** [comment]
Also: https://github.com/jonhoo/fantoccini

**Comment by srid** [comment]
To begin with, we can test that the Nix version is showing up correctly in the DOM (see #12).

**Comment by divinenaman** [comment]
@srid I can take this up

**Comment by srid** [comment]
> @srid can I take this up ?

Sure.

**Comment by divinenaman** [comment]
@srid playwright test also works on darwin

**Comment by srid** [comment]
Replied here, in the context of the PR: https://github.com/juspay/nix-browser/pull/24#issuecomment-1704306132

**Comment by divinenaman** [comment]
@srid separated playwright PR
