### ISSUE TITLE
`nix-health`: `direnv allow` check failure

### ISSUE THREAD

**Issue by shivaraj-bh** [juspay/nix-browser#122]
<img width="986" alt="Screenshot 2024-03-19 at 12 15 41 AM" src="https://github.com/juspay/nix-browser/assets/23645788/9f193771-6e36-49f1-a990-b41cc176c3f8">

The check above fails even though `direnv allow` has been run:
<img width="758" alt="Screenshot 2024-03-19 at 12 15 54 AM" src="https://github.com/juspay/nix-browser/assets/23645788/6ee7a794-5522-4c9b-ab04-9b3cef7841fa">

Here 0 means `Allowed`, for explanation, see: https://github.com/direnv/direnv/pull/1142#issuecomment-1848677532

**Comment by shivaraj-bh** [comment]
`nix-health` [parses the string output](https://github.com/juspay/nix-browser/blob/358f3c444918bc4a577e7e06341173c40e0038e1/crates/nix_health/src/check/direnv.rs#L154), which was fine until there were only two states but now there are more after this [PR](https://github.com/direnv/direnv/pull/1158)

**Comment by srid** [comment]
Want to open a PR?

https://github.com/juspay/nix-browser/blob/358f3c444918bc4a577e7e06341173c40e0038e1/crates/nix_health/src/check/direnv.rs#L154

You added JSON support recently right? We can look for `direnv` version, and check accordingly. Maybe even drop support for older direnv version to keep our code small.
