### ISSUE TITLE
Upgrade to Dioxus 0.5

### ISSUE THREAD

**Issue by srid** [juspay/nix-browser#125]
0.5 ~~is not yet~~ has been released, and the docs are here: https://dioxuslabs.com/learn/0.5/

- No more `cx` argument
- `Signal`s and generally improved state management

Reference PR: https://github.com/srid/dioxus-desktop-template/pull/16

Note: `dioxus-std` is renamed: https://github.com/DioxusLabs/sdk/releases/tag/v0.5.0

**Comment by Mohamed-Ayaan358** [comment]
@srid By any chance are all the issues on the nix-browser repository completed and closed for outside contributors?

**Comment by srid** [comment]
@Mohamed-Ayaan358 Nothing is closed. If you'd like to work on something, drop by our Zulip and ask: https://nixos.zulipchat.com/

**Comment by srid** [comment]
#135
