### ISSUE TITLE
Extract and relicense nix_rs?

### ISSUE THREAD

**Issue by matthiasbeyer** [juspay/nix-browser#127]
Hi,

I would be interested in using your `nix_rs` crate in one of my projects and potentially adding more functionality to it.

Would you be interested in extracting the `nix_rs` crate from this repository and put it into a new repository (I can help with extracting the commit history of the `/crates/nix_rs/` subtree if you want) and release it under another license?
For example `MIT + Apache 2.0` is the most common used license for libraries in the rust ecosystem, or maybe `MPL-2.0` which - to my understanding - is something like GPL but for libraries(, as LGPL does not work for libraries in the rust ecosystem because of static linking).

(all above with "I am not a lawyer" of course).

Would love to hear your opinion on this.

**Comment by srid** [comment]
I can change the license of `nix_rs` (maybe even all of `nix-browser`) to Apache 2.0 ([same as Hyperswitch](https://github.com/juspay/hyperswitch/blob/main/LICENSE)). But I find it convenient to have the library in this monorepo; any particular reason you are requesting a dedicated repo for `nix_rs`?

**Comment by matthiasbeyer** [comment]
Well, if you would relicense all of this repository, I wouldn't see a reason to extract nix_rs to a new repository! :laughing:

**Comment by srid** [comment]
I think I'll make `nix_rs` its own dedicated repo for now, and license it under Apache 2.0.

**Comment by srid** [comment]
@matthiasbeyer You can use this now: https://github.com/juspay/nix-rs/pull/2

I'll close this repo after making nix-browser use the new repo.
