### ISSUE TITLE
Parse Nix version

### ISSUE THREAD

**Issue by srid** [juspay/nix-browser#28]
Currently the dashboard displays whatever `nix --version` returns, which at the moment is:

```
nix (Nix) 2.17.0
```

We just want to extract the "2.17.0". 

Basically implement the TODO here:

https://github.com/juspay/nix-browser/blob/35e75b3b492985f3e8cd2845404e5ba12fdc7e52/src/nix/info.rs#L24-L25

- [ ] Which Rust parser to use? Do we envision parsing more things in the future, and does that affect our choice now?
- [ ] Have the dashboard display the parsed Nix version

**Comment by srid** [comment]
Unless, of course, there are other simpler ways to get the Nix version.

**Comment by shivaraj-bh** [comment]
But Nix will not be following Cargo's flavour of semantic versioning, does it?

**Comment by shivaraj-bh** [comment]
> Do we envision parsing more things in the future, and does that affect our choice now?

We had discussed about parsing json outputs IIRC, i.e the output of `nix eval --json`

**Comment by srid** [comment]
JSON can be parsed with https://docs.rs/serde_json

>  But Nix will not be following Cargo's flavour of semantic versioning, does it?

Nix has simple version formats https://github.com/NixOS/nix/tags - I suppose we can get away with writing our own parsers.

**Comment by shivaraj-bh** [comment]
👍 for writing our own parser for Nix version
