### ISSUE TITLE
`nix_health`: Flake-specific health checks

### ISSUE THREAD

**Issue by srid** [juspay/nix-browser#60]
Each flake can export the metadata (as https://github.com/DeterminateSystems/flake-schemas?) for `nix_health` do checks on. This includes:

- [x] Which Nix caches to check
- [ ] Does the project require/recommend `direnv`? If so, check for `direnv allow` state https://github.com/juspay/nix-browser/issues/70
- [ ] Minimum recommended memory

```nix
{
  flake.nix-health.default.checks = {
    caches.required = [ "nammyatri.cachix.org" ];
    direnv.enable = true;
  };
}
```

Some of these checks (like direnv) will require a specific flake to check against. In the case of direnv, it would also have to be a local path flake.

**Comment by shivaraj-bh** [comment]
Regarding `direnv` health check, this is how I did it in nushell: https://github.com/shivaraj-bh/nix-health/blob/8de00ad118a14f3d3d1b75f296697cb7f9012a26/nix-health.nu#L77-L97

**Comment by srid** [comment]
With #67 we can now configure nix-health behaviour in the project flake as follows:

<img width="462" alt="image" src="https://github.com/juspay/nix-browser/assets/3998/d4d8312d-896f-423b-89c2-1aaaa4734e73">

**Comment by srid** [comment]
This is architecturally in place. #14 will track the specific checks.
