### ISSUE TITLE
Add "open directory" button to open a local flake

### ISSUE THREAD

**Issue by srid** [juspay/nix-browser#85]
Add a "Open directory" button here:

![image](https://github.com/juspay/nix-browser/assets/3998/5e91a3dd-e5fa-4d99-b8f5-41c35b6931f9)

This should ideally bring up the user's [native file-open dialog](https://en.wikipedia.org/wiki/File_dialog) allowing them to select their local project directory. Then the input box is replaced with that local path (eg: `/Users/user/Projects/nammayatri`) which then triggers a reload of the flake info.

## Implementation notes

- Perhaps we can uses Tauri's API to do this: https://tauri.app/v1/api/js/dialog/#open
  - ~~The Rust API seems to miss the 'open' dialog which we may have to contribute? https://docs.rs/tauri/1.5.2/tauri/api/dialog/index.html~~
  - Rust API: https://docs.rs/tauri/latest/tauri/api/dialog/struct.FileDialogBuilder.html

**Comment by shivaraj-bh** [comment]
For starters, I have the frontend sorted:

<img width="1012" alt="Screenshot 2023-10-17 at 7 05 36 PM" src="https://github.com/juspay/nix-browser/assets/23645788/7e618b39-ae76-4215-bfab-73823716144f">

Time to work on the backend now!

**Comment by shivaraj-bh** [comment]
I wasn't able to use `tauri` crate in the project, because of conflicting `gtk-sys` deps, here's the full error:
```
error: failed to select a version for `gtk-sys`.
    ... required by package `rfd v0.10.0`
    ... which satisfies dependency `rfd = "^0.10.0"` of package `nix-browser v0.1.0 (/Users/shivaraj/juspay/nix-browser)`
versions that meet the requirements `^0.15.1` are: 0.15.3, 0.15.1

the package `gtk-sys` links to the native library `gtk-3`, but it conflicts with a previous package which links to `gtk-3` as well:
package `gtk-sys v0.16.0`
    ... which satisfies dependency `gtk-sys = "^0.16"` of package `rfd v0.11.3`
    ... which satisfies dependency `rfd = "^0.11.3"` of package `dioxus-desktop v0.4.2 (https://github.com/DioxusLabs/dioxus.git?rev=459f24d5e9ef0e03a3bbd037342c60bbde409dbf#459f24d5)`
    ... which satisfies git dependency `dioxus-desktop` of package `nix-browser v0.1.0 (/Users/shivaraj/juspay/nix-browser)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='gtk-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `gtk-sys` which could resolve this conflict
```

**Comment by shivaraj-bh** [comment]
Although I believe in `tauri 2.0` they are getting rid of `tauri::api::dialog` and it will be a plugin for tauri, it can be found here: https://github.com/tauri-apps/tauri-plugin-dialog. Tauri plugins looks like a more robust way to integrate features into the app, although I am not sure if it will be easy to integrate this with dioxus apps.

**Comment by shivaraj-bh** [comment]
Here's how loading a local flake looks like:
<img width="1012" alt="Screenshot 2023-10-18 at 5 55 12 PM" src="https://github.com/juspay/nix-browser/assets/23645788/3fcdc707-c9a9-4faa-86af-73a65096208d">
